### ISSUE TITLE
Onboard Katio to Kubernetes services hosted by other cloud vendors

### ISSUE THREAD

**Issue by smritidahal653** [kaito-project/kaito#708]
### Tasks
- [x] #357 
- [x] #360 
- [x] #364 
- [x] #518 
- [x] #602 
- [x] Test: verify Kaito works on AWS using self-provisioned gpu-nodes
- [x] Test: verify Kaito works on AWS with Karpenter integration
- [x] Test: verify nodeClaim can be created using default Nodepool
- [x] #710 
- [x] #711

**Comment by Fei-Guo** [comment]
We need to work on an onboarding strategy for different cloud vendors (clouds with Karpenter support, clouds without Karpenter support, etc.) 
e.g., what the process or things need to be checked when claim kaito support different cloud vendors?

**Comment by ritazh** [comment]
Per community call, consider provider-based model similar to kubernetes cloud provider and other OSS projects: 
https://secrets-store-csi-driver.sigs.k8s.io/providers
https://open-policy-agent.github.io/gatekeeper/website/docs/externaldata#providers

**Comment by chewong** [comment]
Duplicate of #452
